### ISSUE TITLE
No such file or directory: 'ckpts/ultra_4g.pth'

### ISSUE THREAD

**Issue by sauravjoshi23** [DeepGraphLearning/ULTRA#3]
## Error
When I run script/run.py in any setting I get the following error on colab.
```
/content/ULTRA
18:57:37   Random seed: 1024
18:57:37   Config file: config/inductive/inference.yaml
18:57:37   {'checkpoint': 'ckpts/ultra_4g.pth',
 'dataset': {'class': 'FB15k237Inductive',
             'root': '~/git/ULTRA/kg-datasets/',
             'version': 'v1'},
 'model': {'class': 'Ultra',
           'entity_model': {'aggregate_func': 'sum',
                            'class': 'IndNBFNet',
                            'hidden_dims': [64, 64, 64, 64, 64, 64],
                            'input_dim': 64,
                            'layer_norm': True,
                            'message_func': 'distmult',
                            'short_cut': True},
           'relation_model': {'aggregate_func': 'sum',
                              'class': 'NBFNet',
                              'hidden_dims': [64, 64, 64, 64, 64, 64],
                              'input_dim': 64,
                              'layer_norm': True,
                              'message_func': 'distmult',
                              'short_cut': True}},
 'optimizer': {'class': 'AdamW', 'lr': 0.0005},
 'output_dir': '~/git/ULTRA/output',
 'task': {'adversarial_temperature': 1,
          'metric': ['mr', 'mrr', 'hits@1', 'hits@3', 'hits@10', 'hits@10_50'],
          'name': 'InductiveInference',
          'num_negative': 256,
          'strict_negative': True},
 'train': {'batch_per_epoch': None,
           'batch_size': 16,
           'gpus': [0],
           'log_interval': 100,
           'num_epoch': 0}}
18:57:37   FB15k237Inductive(v1) dataset
18:57:37   #train: 4245, #valid: 489, #test: 411
DEBUG
/root/git/ULTRA/output/Ultra/FB15k237Inductive/2023-10-26-18-57-37
ckpts/ultra_4g.pth
Traceback (most recent call last):
  File "/content/ULTRA/script/run.py", line 271, in <module>
    state = torch.load(cfg.checkpoint, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/ultra_4g.pth'
```
## Solution

In order to fix it and get it running, I had to initialize the model before setting up the working_dir. Essentially the working dir changes the path and it is not able to recognize the checkpoint path passed via args.

```
if __name__ == "__main__":
    print(os.getcwd())
    args, vars = util.parse_args()
    cfg = util.load_config(args.config, context=vars)
    model = Ultra(
        rel_model_cfg=cfg.model.relation_model,
        entity_model_cfg=cfg.model.entity_model,
    )

    print("DEBUG")
    print(os.getcwd())
    print(cfg.checkpoint)
    if "checkpoint" in cfg and cfg.checkpoint is not None:
        state = torch.load(cfg.checkpoint, map_location="cpu")
        model.load_state_dict(state["model"])
    working_dir = util.create_working_directory(cfg)
```

**Comment by migalkin** [comment]
What's your command line? The Readme says you should use a full path to the checkpoint, eg, 
```--ckpt /full/path/to/ULTRA/ckpts/ultra_4g.pth``` 
instead of 
```--ckpt ckpts/ultra_4g.pth```
